"""Add exclusive cards model, is_featured to listings, is_popular to categories

Revision ID: a2a0acd07cf7
Revises: 44ec30f3a4a6
Create Date: 2026-03-26 19:41:00.647649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a0acd07cf7'
down_revision: Union[str, None] = '44ec30f3a4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusive_cards',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Main header text displayed on the card'),
    sa.Column('tag', sa.String(length=50), nullable=False, comment="Tag label (e.g., 'Daily Fire', 'Exclusive')"),
    sa.Column('button_text', sa.String(length=100), nullable=False, comment='Text displayed on the call-to-action button'),
    sa.Column('button_link', sa.String(length=500), nullable=False, comment='URL or route to navigate when button is clicked'),
    sa.Column('background_type', sa.String(length=20), nullable=False, comment="Type of background: 'image' or 'gradient'"),
    sa.Column('background_value', sa.String(length=500), nullable=False, comment='Image URL or CSS gradient value'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the card is currently visible'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Display order for sorting (lower values appear first)'),
    sa.Column('display_until', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration date after which card is hidden'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusive_cards_is_active'), 'exclusive_cards', ['is_active'], unique=False)
    op.add_column('categories', sa.Column('is_popular', sa.Boolean(), nullable=False, comment='Whether this category is shown in popular games section'))
    op.create_index(op.f('ix_categories_is_popular'), 'categories', ['is_popular'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_is_popular'), table_name='categories')
    op.drop_column('categories', 'is_popular')
    op.drop_index(op.f('ix_exclusive_cards_is_active'), table_name='exclusive_cards')
    op.drop_table('exclusive_cards')
    # ### end Alembic commands ###
