"""Schemas module for the Game Account Marketplace."""

from app.schemas.account import (
    AccountDetailResponse,
    AccountFeatureSchema,
    AccountFiltersSchema,
    AccountResponse,
    AccountsBrowseResponse,
    PriceRangeSchema,
    SellerInfoSchema,
    SimilarAccountsResponse,
)
from app.schemas.common import (
    APIResponse,
    ErrorDetail,
    ErrorResponse,
    PaginationSchema,
    SuccessResponse,
)
from app.schemas.deal import (
    AccountFullSchema,
    AccountSummarySchema,
    ConfirmPaymentRequest,
    CreateDealRequest,
    DealDetailResponse,
    DealResponse,
    DealStatus,
    MediatorSummarySchema,
    PaymentInfoSchema,
    PaymentStatus,
    PaymentStatusResponse,
    RejectPaymentRequest,
    SubmitPaymentRequest,
    UpdateDealStatusRequest,
    UserSummarySchema,
)
from app.schemas.mediator import (
    MediatorBadgeSchema,
    MediatorDetailResponse,
    MediatorFiltersSchema,
    MediatorResponse,
    MediatorReviewSchema,
    MediatorReviewsResponse,
    MediatorStatsSchema,
    MediatorTier,
    PaymentMethodSchema,
    PaymentMethodType,
)
from app.schemas.user import (
    ChangePasswordRequest,
    ConfirmResetPasswordRequest,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    ResetPasswordRequest,
    UserBase,
    UserCreate,
    UserResponse,
    UserStatsSchema,
    UserUpdate,
    UserWithStatsResponse,
    VerifyEmailRequest,
)

__all__ = [
    # Common
    "PaginationSchema",
    "APIResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserStatsSchema",
    "UserWithStatsResponse",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "ChangePasswordRequest",
    "ResetPasswordRequest",
    "ConfirmResetPasswordRequest",
    "VerifyEmailRequest",
    # Account
    "AccountFeatureSchema",
    "SellerInfoSchema",
    "AccountResponse",
    "AccountDetailResponse",
    "AccountsBrowseResponse",
    "SimilarAccountsResponse",
    "AccountFiltersSchema",
    "PriceRangeSchema",
    # Mediator
    "MediatorTier",
    "PaymentMethodType",
    "PaymentMethodSchema",
    "MediatorBadgeSchema",
    "MediatorResponse",
    "MediatorDetailResponse",
    "MediatorStatsSchema",
    "MediatorReviewSchema",
    "MediatorReviewsResponse",
    "MediatorFiltersSchema",
    # Deal
    "DealStatus",
    "PaymentStatus",
    "CreateDealRequest",
    "AccountSummarySchema",
    "AccountFullSchema",
    "MediatorSummarySchema",
    "UserSummarySchema",
    "PaymentInfoSchema",
    "DealResponse",
    "DealDetailResponse",
    "UpdateDealStatusRequest",
    "SubmitPaymentRequest",
    "PaymentStatusResponse",
    "ConfirmPaymentRequest",
    "RejectPaymentRequest",
]
